name: ball_scout
description: 球探社 - 中国最纯净的足球资讯聚合平台
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 网络请求
  http: ^1.2.2
  dio: ^5.8.0
  
  # 状态管理
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # 本地存储
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI组件
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh: ^2.0.0
  
  # 导航
  go_router: ^15.2.3
  
  # 工具类
  intl: ^0.20.2
  url_launcher: ^6.2.6
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  
  # JSON序列化
  json_annotation: ^4.8.1
  
  # 图片选择
  image_picker: ^1.1.2
  
  # 推送通知（暂时注释，避免依赖问题）
  # firebase_messaging: ^14.7.9
  # flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 代码生成
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  
  # 代码检查
  flutter_lints: ^6.0.0
  
  # 图标生成（暂时注释）
  # flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # 暂时注释assets，后续添加
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/logos/
  
  # 暂时注释字体，使用系统默认字体
  # fonts:
  #   - family: PingFang
  #     fonts:
  #       - asset: assets/fonts/PingFang-Regular.ttf
  #       - asset: assets/fonts/PingFang-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/PingFang-Semibold.ttf
  #         weight: 600
  #       - asset: assets/fonts/PingFang-Bold.ttf
  #         weight: 700

# 暂时注释图标配置
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/ball_scout_icon.png"
#   min_sdk_android: 21
#   web:
#     generate: true
#     image_path: "assets/icon/ball_scout_icon.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "assets/icon/ball_scout_icon.png"
#     icon_size: 48 